### PR TITLE
Search bar

### PR DESCRIPTION
**Pull request by gislawill**
Adding a location search bar to the top left panel that gives suggestions and flys to selected locations

https://github.com/CoastalResilienceExplorer/GlobalFloodExplorer/assets/8203830/d4250ccc-e9a1-4032-bd47-5b6dabc50057

### CODE REVIEW

**Comment by lowriech** [comment]
Getting the following error:
```
ERROR in src/panels/home-info-panel/search-bar.tsx:61:28
TS2304: Cannot find name 'google'.
    59 |             status: google.maps.places.PlacesServiceStatus,
    60 |           ) => {
  > 61 |             if (status === google.maps.places.PlacesServiceStatus.OK) {
       |                            ^^^^^^
    62 |               resolve(predictions);
    63 |             } else reject(status);
    64 |           },
    ```

Looks like not defined as a dependency and imported?

**Comment by gislawill** [comment]
> Getting the following error:
> 
> ```
> ERROR in src/panels/home-info-panel/search-bar.tsx:61:28
> TS2304: Cannot find name 'google'.
>     59 |             status: google.maps.places.PlacesServiceStatus,
>     60 |           ) => {
>   > 61 |             if (status === google.maps.places.PlacesServiceStatus.OK) {
>        |                            ^^^^^^
>     62 |               resolve(predictions);
>     63 |             } else reject(status);
>     64 |           },
> ```
> 
> Looks like not defined as a dependency and imported?

@lowriech updated the typescript config and we should be all good 👍  Also fixed the video demo

**Comment by lowriech** [comment]
Love the search bar functionality.  Let's hold on this until we can discuss, I want to see if JKB can attend our Tuesday meet and give design feedback.

**Comment by gislawill** [comment]
tis fixed

**Pull request merged**
