### PR TITLE
Updated color pallet

### PR DESCRIPTION
**Pull request by lowriech**
Check it out, adding new color palettes.  

**Existing Risk**
image

**Benefits**
image

**Risk Reduction Ratio**
image

**Flooding** *
image

**Population**
image

### CODE REVIEW

**Comment by lowriech** [comment]
@gislawill One outstanding thing is the flood styling.  Basically, we've said we want Green for mangroves and Red for flooding, which is colorblind unfriendly.  Wondering if you have any thoughts here?

**Comment by gislawill** [comment]
> @gislawill One outstanding thing is the flood styling. Basically, we've said we want Green for mangroves and Red for flooding, which is colorblind unfriendly. Wondering if you have any thoughts here?

My understanding is the best practice is to give multiple methods to differentiate when using risky color combination 

A few options to consider:
- Put a border around mangroves polygons to differentiate 
  - Could be a dark gray or even dark green
- Put a fill texture in the mangroves polygons to differentiate
  - Squiggles or waves?
- Use a different color for flooding
  - I could see yellow -> blue working

These are loosely in order of what I'd recommend

**Comment by gislawill** [comment]
It looks like we have multiple levels of mangroves now (green and light green). It is definitely interesting data but I'm not sure it's useful in this context. Without a scale or description of what it represents, I find it a bit distracting 
Screenshot 2024-08-02 at 1 04 53 PM

**Comment by lowriech** [comment]
Hmm noted.  The multiple shades of green just comes from the borders, I'll remove them.

I think I'll go for the pattern approach, and a better border/outline

**Review by gislawill — APPROVED** [review]

**Pull request merged**
