### PR TITLE
Cogmaker service

### PR DESCRIPTION
**Pull request by lowriech**
**COG Maker**
I've wired up a bucket to automatically generate COGs (Cloud-Optimized Geotiffs).  The service stack is
- Cloud Storage
- Eventarc, to trigger Cloud Run on storage events
- Cloud Run, to generate COGs from regular Tiffs

**TODOs**
There are a few TODOs before I feel comfortable putting this in main.  We should set up some time to discuss so that we're both familiar with the architecture.  Could also use a review on how we like the CI structure of this.  I don't expect to merge this PR, but want to collaborate on the service.

**Services**
There's also some work to have a services structure, so we can trigger builds on a specific set of independent services.  It's not quite there yet, but the idea is to have a base image that only has to be rebuilt once in a while, and then services that build from that using Cloud Build.  

**Note** that this is currently wired up to a build trigger I manually created on the `staging` branch, which runs a small test of the service (but doesn't yet have good error reporting).

**About COGs**
COGs are a very nice way to access geospatial data in a web-friendly way, and the most promising use case for us hosting the flood layers.  Basically it's a regular Geotiff, totally usable in all the same way, but its internal structure allows for easy access in a tiled manner.  You can access them directly from GCS, which is very nice for separation of compute and storage.

### CODE REVIEW

**Comment by gislawill** [comment]
This is awesome! That COG server is both dead simple and super 🔥. Ok, my python is a little rusty but am I correct that it generates a COG out of any file that added to a specific bucket and re-uploads the geotiffs to the same bucket? And we always have a python server running waiting for Eventarc trigger? 

A few questions:
- What part is terraform handling for us?
- Is there any scaling of geotiffs we should perform to make sure they're sized appropriately?

A few suggestions:
- Rather than an always running server, could we use this trigger to run a script?
  - Usually easier to maintain a script than a server
  - A script that fails can be rerun again, a server that fails needs to be restarted
- I think it'd be helpful to do some slight validation on the user-uploaded file before transforming to make sure it's the right type
- I think we should house this in a separate repo because it's a pretty isolated and separate from the web ui
- Let's .gitignore everything in the test directory

**Comment by lowriech** [comment]
So it doesn't run a server, it uses eventarc+Cloud Run+GCS.  Eventarc is kind of like a PubSub manager, so it just connects a storage event to a cloud run service.  Drop a file in a bucket, send that file's name to Cloud Run, Cloud Run processes and drops into another bucket.  Because of this, there's not really a way to validate the submitted Geotiff, other than when it reaches the Cloud Run service.  But we should do some checks there to just make sure it's a Geotiff.

I also had to add a front service to get around PubSub acknowledgement timeouts, now we can run up to an hour which means we can process global high-res (at least 250m, maybe smaller).  

There's actually no terraform in this, I just made a trigger by hand in Cloud Console.  `cloudbuild.yaml` and `build_and_submit.sh` are basically doing all the work.

A separate repo makes sense, since this could apply to other projects as well.  Let's find some time to chat about this, maybe next week?

**Comment by gislawill** [comment]
@lowriech would you have time to chat tomorrow evening? I'll be away from my computer the evening of Aug 19 through the evening of Aug 26

**Comment by lowriech** [comment]
@gislawill Check this out when you have a sec.  Also posted a corresponding video in Slack describing what is going on.

**Pull request merged**
